In [17]:
# importing modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import glob

In [18]:
# importing CSV files using glob

# importing all the csv files in the project directory using glob and regex to find the relevant files
# * is a regex quantifier which enables one to select the preceeding character 0 or more times
# im not exactly sure why this quantifer was able to select files states.csv 0 - 9
# I tried using other regex expressions however the kleene star was the one which worked

files = glob.glob('states*.csv')

In [19]:
# creating a dataframe from the files using pandas and pd.concat to combine the dataframes into one dataframe

dataframes = []
for filename in files:
    data = pd.read_csv(filename)
    dataframes.append(data)
    
us_census = pd.concat(dataframes)

# Inspecting the DataFrame

#### Things to Do

- remove column: unnamed 0 

- demographics columns
1. remove percent sign
2. convert from string to float
3. possibly rename columns to be more descriptive
4. some rows have missing info either the missing info could be changed to zero or possibly use the total population minus the percent missing to fill in the missing rows
5. some rows are duplicated we need to remove these rows

- change income column from string to float

- column gender_pop 
1. split male and female data into seperate columns
2. some columns have missing info. gender_pop column is closely related to total population. use total population to help find missing info


### Note to self

When dropping columns save the result to a new variable do not drop inplace

In [20]:
# copy of dataframe
# this is the dataframe I will be editing throughout the project
census_data = us_census.copy()

In [21]:
# Remove the $ in the income column
census_data['Income'] = census_data['Income'].apply(lambda x: x.replace('$', ''))

# convert data to a float
census_data['Income'] = pd.to_numeric(census_data['Income'])
# round data to 2 decimals since we are dealing with money
census_data['Income'] = census_data['Income'].round(2)
# rename income column to Income $
census_data = census_data.rename(columns={'Income': 'Income ($)'})

In [22]:
# deleted the column unnamed: 0 from the dataframe
census_data_edited = census_data.drop(columns='Unnamed: 0')

# deleted the duplicated rows and reset_index
census_data_edited_2 = census_data_edited.drop_duplicates().reset_index()
census_data_edited_3 = census_data_edited_2.drop(columns='index')

In [30]:
# Split the genderpop column into a series containing a list with two indexes male and female
genpop_series = census_data_edited_3['GenderPop'].str.split('_')

# Adding Male Population and Female Population columns to dataframe
census_data_edited_3['Male Population'] = genpop_series.str[0]
census_data_edited_3['Female Population'] = genpop_series.str[1]

# Removing the genderpop column
census_data_edited_4 = census_data_edited_3.drop(columns='GenderPop')


# Remove 'M' and 'F' from gender columns and convert them to int from strings
census_data_edited_4['Male Population'] = census_data_edited_4['Male Population'].apply(lambda x: x.replace('M', ''))
census_data_edited_4['Female Population'] = census_data_edited_4['Female Population'].apply(lambda x: x.replace('F', ''))

census_data_edited_4.head(5)

,State,TotalPop,Hispanic,White,Black,Native,Asian,Pacific,Income ($),Male Population,Female Population
0,Alabama,4830620,3.7516156462584975%,61.878656462585%,31.25297619047618%,0.4532312925170065%,1.0502551020408146%,0.03435374149659865%,43296.36,2341093,2489527
1,Alaska,733375,5.909580838323351%,60.910179640718574%,2.8485029940119775%,16.39101796407186%,5.450299401197604%,1.0586826347305378%,70354.74,384160,349215
2,Arizona,6641928,29.565921052631502%,57.120000000000026%,3.8509868421052658%,4.35506578947368%,2.876578947368419%,0.16763157894736833%,54207.82,3299088,3342840
3,Arkansas,2958208,6.215474452554738%,71.13781021897813%,18.968759124087573%,0.5229197080291965%,1.1423357664233578%,0.14686131386861315%,41935.63,1451913,1506295
4,California,38421464,37.291874687968054%,40.21578881677474%,5.677396405391911%,0.40529206190713685%,13.052234148776776%,0.35141038442336353%,67264.78,19087135,19334329